#!/usr/bin/env bash
set -e

docker_args=(
  run
  --rm
  -it
  -e HOME=/tmp
  -e GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/tmp/known_hosts -o StrictHostKeyChecking=accept-new"
  -v "$PWD:/work"
  -w /work
)

if [ -f "$HOME/.gitconfig" ]; then
  docker_args+=(
    -v "$HOME/.gitconfig:/tmp/.gitconfig:ro"
  )
fi

if [ -n "${SSH_AUTH_SOCK:-}" ] && [ -S "$SSH_AUTH_SOCK" ]; then
  docker_args+=(
    -v "$SSH_AUTH_SOCK:/ssh-agent"
    -e SSH_AUTH_SOCK=/ssh-agent
  )
fi

docker "${docker_args[@]}" @@WORK_IMAGE@@ "$@"
