#!/usr/bin/env bash
set -e

docker_args=(
  run
  --rm
  -it
  -u "$(id -u):$(id -g)"
  -e HOME=/tmp
  -v "$PWD:/work"
  -w /work
)

if [ -f "$HOME/.gitconfig" ]; then
  docker_args+=(
    -v "$HOME/.gitconfig:/tmp/.gitconfig:ro"
  )
fi

if [ -d "$HOME/.ssh" ]; then
  docker_args+=(
    -v "$HOME/.ssh:/tmp/.ssh:ro"
  )
fi

docker "${docker_args[@]}" @@WORK_IMAGE@@ "$@"
